
name: main_workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: push trigger
        # Save commit url from GitHub Trigger event payload to URL env
        if: "contains(github.event_name, 'push')"
        run: |
          url=${{ github.event.head_commit.url }}
          echo "URL=$url" >> "$GITHUB_ENV"
      - name: pull request trigger
        # Save pull request url from GitHub Trigger event payload to URL env
        if: "contains(github.event_name, 'pull_request')"
        run: |
          url=${{ github.event.pull_request.url }}
          echo "URL=$url" >> "$GITHUB_ENV"
