
name: test_workflow_notify

on:
  push:
    branches: [ alert_test ]
  pull_request:
    branches: [ alert_test ]

env:
  ACTION_URL: "https://github.com/Quansight/scrape_harvest/actions/runs"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: push trigger
        # Save commit url from GitHub Trigger event payload to URL env
        if: "contains(github.event_name, 'push')"
        run: |
          url=${{ github.event.head_commit.url }}
          echo "URL=$url" >> "$GITHUB_ENV"
      - name: pull request trigger
        # Save pull request url from GitHub Trigger event payload to URL env
        if: "contains(github.event_name, 'pull_request')"
        run: |
          url=${{ github.event.pull_request.url }}
          echo "URL=$url" >> "$GITHUB_ENV"
      - name: Check status
        run: |
          if [[ $status == "success" ]]; then 
            MSG=":white_check_mark: *Scrape harvest: ${{ job.status }}*\n>Run details: ${{ env.ACTION_URL }}/${{ github.run_id }}"
          else
            MSG=":x: *Scrape harvest: ${{ job.status }}*\n>Run details: ${{ env.ACTION_URL }}/${{ github.run_id }}"
          fi
      - name: Send GitHub Action trigger data to Slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
            {
              "text": ${{ env.MSG }}
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
