
name: test_workflow_notify

on:
  push:
    branches: [ more_tests ]
  pull_request:
    branches: [ more_tests ]

env:
  BRANCH: "manual_action_test"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}

      - name: Tag the current branch
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
