
name: test_workflow_notify

on:
  push:
    branches: [ more_tests ]
  pull_request:
    branches: [ more_tests ]

env:
  BRANCH: "manual_action_test"
  IMG_REPO: "registry.gitlab.com/openteams/automation-and-integration/backlog"
  BUILD_ID: "12345"
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}

      - name: Tag the current branch
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push

  deploy:
    needs: build
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Display Image name
        debug:
          msg: 
          - "QADMIN: {{ env.IMG_REPO }}/qadmin:{{ env.BUILD_ID }}"
          - "PROXY: {{ env.IMG_REPO }}/proxy:{{ env.BUILD_ID }}"

      - name: Display Image name
        debug:
          msg: "Hello hello"
      
     

