
name: test_workflow_notify

on:
  push:
    branches: [ alert_test ]
  pull_request:
    branches: [ alert_test ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: push trigger
        # Save commit url from GitHub Trigger event payload to URL env
        if: "contains(github.event_name, 'push')"
        run: |
          url=${{ github.event.head_commit.url }}
          echo "URL=$url" >> "$GITHUB_ENV"
      - name: pull request trigger
        # Save pull request url from GitHub Trigger event payload to URL env
        if: "contains(github.event_name, 'pull_request')"
        run: |
          url=${{ github.event.pull_request.url }}
          echo "URL=$url" >> "$GITHUB_ENV"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
            {
              "text": "*Scrape harvest job: ${{ job.status }}*\n>Details see: ${{ env.URL }}. github.action_path: ${{ github.action_path }}, github.job ${{ github.job }} github.run_id: ${{ github.run_id }}  "
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

