
name: test_workflow_notify

on:
  push:
    branches: [ more_tests ]
  pull_request:
    branches: [ more_tests ]

env:
  BRANCH: "manual_action_test"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "$BRANCH"

      - name: tag current commit
        

      - name: push trigger
        # Save commit url from GitHub Trigger event payload to URL env
        if: "contains(github.event_name, 'push')"
        run: |
          url=${{ github.event.head_commit.url }}
          echo "URL=$url" >> "$GITHUB_ENV"
      - name: pull request trigger
        # Save pull request url from GitHub Trigger event payload to URL env
        if: "contains(github.event_name, 'pull_request')"
        run: |
          url=${{ github.event.pull_request.url }}
          echo "URL=$url" >> "$GITHUB_ENV"
      - name: Send GitHub Action trigger data to Slack - Success
        if: ${{ success() }} 
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
            {
              "text": ":white_check_mark: *Scrape harvest: ${{ job.status }}*\n>Run details: ${{ env.ACTION_URL }}/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Send GitHub Action trigger data to Slack - Others
        if: ${{ !success() }} 
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
            {
              "text": ":x: *Scrape harvest: ${{ job.status }}*\n>Run details: ${{ env.ACTION_URL }}/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
