name: test_workflow_notify

on:
  push:
    branches: [ alert_test ]
  pull_request:
    branches: [ alert_test ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: push trigger
        # Save commit url from GitHub Trigger event payload to URL env
        if: "contains(github.event_name, 'push')"
        run: |
          url=${{ github.event.head_commit.url }}
          echo "URL=$url" >> "$GITHUB_ENV"
      - name: pull request trigger
        # Save pull request url from GitHub Trigger event payload to URL env
        if: "contains(github.event_name, 'pull_request')"
        run: |
          url=${{ github.event.pull_request.url }}
          echo "URL=$url" >> "$GITHUB_ENV"
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: "{\"text\":\"Incoming Webhook test for slack send\", \"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"plain_text\",\"text\":\"A post by Slack Send GitHub Action. Testing Incoming webhooks\",\"emoji\":true}}]}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

